import { GoogleGenAI, Type } from "@google/genai";
import type { Schema } from "@google/genai";
import type { CopilotContext, CopilotResult } from "../types/ai";

export async function runGeminiCopilot(
  command: string,
  ctx: CopilotContext,
  lang: "en" | "es"
): Promise<CopilotResult | null> {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("VITE_GEMINI_API_KEY not found. Falling back to deterministic copilot.");
    return null; // Signals fallback
  }

  try {
    const ai = new GoogleGenAI({ apiKey });

    // Ensure the system prompt explicitly requests the structured schema
    const sysPrompt = `
You are the central AI coordinator for a planetary-scale digital infrastructure command center.
Your job is to analyze telemetry and respond to the Commander's requests in ${lang === "es" ? "Spanish" : "English"}.
You must always output your response as valid JSON matching the requested schema.

CURRENT TELEMETRY:
- Incidents: ${ctx.metrics.incidents}
- Cyber Risk: ${(ctx.metrics.cyberRisk * 100).toFixed(1)}%
- Resilience: ${(ctx.metrics.resilience * 100).toFixed(1)}%
- Active Scenario: ${ctx.scenario ? ctx.scenario.title.en : "None"}

When asked to mitigate, isolate, or resolve an issue, set "action" to "clear_scenario".
Otherwise, provide a concise analysis.
`;

    const schema: Schema = {
      type: Type.OBJECT,
      properties: {
        intent: { type: Type.STRING, description: "Short intent name (e.g. 'sim', 'action', 'analysis')" },
        action: { type: Type.STRING, description: "Action to take. Set to 'clear_scenario' to mitigate an ongoing crisis." },
        riskLevel: { type: Type.STRING, description: "Nominal, Low, Elevated, High, Critical" },
        executiveSummary: { type: Type.STRING, description: "2 sentence summary" },
        affectedRegions: { type: Type.ARRAY, items: { type: Type.STRING } },
        affectedServices: { type: Type.ARRAY, items: { type: Type.STRING } },
        affectedAIWorkflows: { type: Type.ARRAY, items: { type: Type.STRING } },
        businessImpact: { type: Type.STRING },
        recommendedAction: { type: Type.STRING },
        humanApprovalRequired: { type: Type.BOOLEAN },
        next48Hours: { type: Type.ARRAY, items: { type: Type.STRING } }
      },
      required: ["intent", "riskLevel", "executiveSummary"]
    };

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: command,
      config: {
        systemInstruction: sysPrompt,
        responseMimeType: "application/json",
        responseSchema: schema,
        temperature: 0.2
      }
    });

    if (!response.text) return null;

    const out = JSON.parse(response.text);
    
    // Map AgentOutput to Report
    const report = {
      title: out.intent.toUpperCase() + " / GEMINI RAG",
      level: out.riskLevel,
      lines: [
        { k: lang === "es" ? "Resumen Ejecutivo" : "Executive Summary", v: out.executiveSummary },
        { k: lang === "es" ? "Regiones" : "Regions", v: out.affectedRegions?.join(", ") || "-" },
        { k: lang === "es" ? "Servicios" : "Services", v: out.affectedServices?.join(", ") || "-" },
        { k: lang === "es" ? "IAs/Workflows" : "AI/Workflows", v: out.affectedAIWorkflows?.join(", ") || "-" },
        { k: lang === "es" ? "Impacto Negocio" : "Business Impact", v: out.businessImpact || "-" },
        { k: lang === "es" ? "Acción Sugerida" : "Suggested Action", v: out.recommendedAction || "-" },
        { k: lang === "es" ? "Requiere Aprobación" : "Approval Required", v: out.humanApprovalRequired ? "SÍ" : "NO", lvl: out.humanApprovalRequired ? "critical" : undefined },
        { k: "48h", v: out.next48Hours?.join("; ") || "-" }
      ]
    };

    return {
      command: { id: out.action === "clear_scenario" ? "action" : "claude" },
      report,
      note: "Generated by Gemini API."
    };
  } catch (error) {
    console.error("Gemini Copilot Error:", error);
    return null; // Fallback
  }
}
